### ISSUE TITLE
Remove mariadb installation

### ISSUE THREAD

**Issue by gildasio** [hackinsdn/dvwa#3]
It would be better to only have DVWA setup but MariaDB was needed because I wasn't able to set lab topology with mariadb separately in another container.

https://github.com/digininja/DVWA/blob/3587fb51cfca2ebca5b9bee5545b5aeaff0978f7/compose.yml

**Comment by gildasio** [comment]
Nowadays mininet-sec requires `iproute2` and `net-tools` packages in order to correctly configure nodes' IP addresses.

So, in order to close this issue we need to:

- Create a personalized mariadb docker image installing those packages; or
- Change the way mininet-sec configure networking

The `gjuniioor/dvwa-socat:mariadb` Dockerfile:

```
FROM mariadb:10

RUN apt update \
 && apt install -y --no-install-recommends net-tools \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 3306
```

The `gjuniioor/dvwa-socat:only_socat` Dockerfile:

```
FROM ghcr.io/digininja/dvwa:latest

RUN apt update \
 && apt install -y --no-install-recommends socat net-tools iproute2 \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 80

COPY start.sh /start.sh
CMD ["/start.sh"]
```

And its usage by a manifest file:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-custom-topo-${pod_hash}
data:
  customTopology.yaml: |-
    name: my custom topology
    defaults:
      env:
        DEFENVVAR1: xpto
    hosts:
      secflood:
        ip: 192.168.0.10/24
        defaultRoute: via 192.168.0.1
        kind: k8spod
        image: hackinsdn/secflood:latest
        publish: ["8443:443"]
        env:
        - name: SECFLOOD_INTF_INSIDE
          value: secflood-eth0
        - name: SECFLOOD_GW_INSIDE
          value: 192.168.0.1
        - name: SECFLOOD_INTF_OUTSIDE
          value: secflood-eth0
      dvwa:
        ip: 192.168.0.20/24
        defaultRoute: via 192.168.0.1
        kind: k8spod
        image: gjuniioor/dvwa-socat:only_socat
        publish: ["8080:80"]
        depends_on:
        - db
        env:
        - name: DB_SERVER
          value: 192.168.0.30
      db:
        ip: 192.168.0.30/24
        defaultRoute: via 192.168.0.1
        kind: k8spod
        image: gjuniioor/dvwa-socat:mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dvwa
        - name: MYSQL_DATABASE
          value: dvwa
        - name: MYSQL_USER
          value: dvwa
        - name: MYSQL_PASSWORD
          value: p@ssw0rd
    switches:
      s1:
        kind: lxbr
    links:
      - node1: secflood
        node2: s1
      - node1: dvwa
        node2: s1
      - node1: db
        node2: s1
```
